### PR TITLE
added display of lines in selections

### PR DESCRIPTION
**Pull request by Kerollmops**

### CODE REVIEW

**Comment by frabert** [comment]
It is almost perfect! One thing, though: you should let APM do the version change, so the `version` in package.json should be reverted, and in the CHANGELOG the version listed should be 0.2.0, according to _semver_, since you added features. Then I can merge! Now I have to find a way to install APM without atom...

**Comment by frabert** [comment]
Now all it needs is some updated specs. I will look into it as soon as I can.

**Comment by Kerollmops** [comment]
Ok thanks mate !

**Comment by Kerollmops** [comment]
When did you think you will update the package on atom ?

**Comment by frabert** [comment]
I am currently installing IOjs & npm & apm & everything on my old MB on a crappy internet connection, so I don't really know for sure. For now, though, you can patch your local package to have the functionalities you need without having to wait for an update :cool:

**Comment by Kerollmops** [comment]
Ok that's what I have already done, but that's cleanest to use the real repo ! ;)
but thanks ! I am not in a hurry ^^

**Pull request merged**
